### ISSUE TITLE
Not converge & Forward kinematics in FK.m

### ISSUE THREAD

**Issue by xjtu19** [Alcatrazee/Robot_calibration_algorithm#1]
Why the forward kinematics in FK.m is not the end-effector configuration in the base frame?

I go through the code and find that T_link_abs(:,:,i) = eye(4);  is unit matrix rather than the initial configuration of end-effector, like gst0.

Follow your code in FK.m, I can't get right configuration of my end-effector. It is not consistent with the code IKinBody.m in the book _Modern Robotics_  from Lynch.

Especially, I sampled several 3D points of my end-effector, I replaced T_a = T_a*g_st0_a; (in cali_2016.m) with my points represented in the base frame, but the code cannot converge. 

How to solve this problem?  Thank you!

**Comment by Alcatrazee** [comment]
In FK.m, the output is (T,T_link_incr,T_link_abs), which, T , is the transformation of pose of any frame w.r.t base frame, e.g. the tip pose in base frame in initial pose ( g_st0) multiply by T ,like T*g_st0, is equal  to the tip pose in base frame with T( made by twist and joints' angles)

T_link_abs is not the  EE pose, T_link_abs only represents the list of  transformation of a pose after motion of each joint, e.g. T1*T2 represents the pose of unit matrix after motion of transforming by joint 1 and 2. 

Finally, I don't know what your dataset is , but if you want to use your own data in this algorithm, try another repo. named [Robot_calibration](https://github.com/Alcatrazee/Robot_calibration/tree/master)
/ACS_on_two_dataset.m , it should give you a direct guild to access your own datasets due to I had set the real data input as a file.

Also, you should refer to the book named ”A Mathematical Introduction to Robotic Manipulation“ written by [Richard M. Murray] [Zexiang Li] , because I replicated these papers with the help of former RA of Zexiang Li's.

Good luck!

**Comment by xjtu19** [comment]
Many thanks to your kind reply!
This repo and the [Robot_calibration](https://github.com/Alcatrazee/Robot_calibration/tree/master), especialy the simulated robot  calibration in the software, helped me a lot, and it will take me a few days to master them.
These are precious works in this field since I couldn't find more~~
Thanks again! ^_^

**Comment by Alcatrazee** [comment]
It's good to help.
